# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  图图
subtitle: 莫道桑榆晚，为霞尚满天
name: 图图
email: 18510894615@163.com
description: 莫道桑榆晚，为霞尚满天
keywords: 不以物喜，不以己悲
encoding: "utf-8"
favicon: favicon.ico 

repository: niukouzz/niukou.github.io
github_url: https://github.com/niukouzz
url: https://niukou.github.io
enforce_ssl: niukou.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: http://itmooc.tech/
    label: A
    target: _blank  

  -
    href: /money.html
    label: B
    target: _self   

  -
    href: /it.html
    label: C
    target: _self

  -
    href: /life.html
    label: D
    target: _self

  -
    href: /arch.html
    label: E
    target: _self

  -
    href: /link.html
    label: F
    target: _self

  -
    href: /about.html
    label: G
    target: _self


